version: '2'

services:
  nginx:
    container_name: nginx
    image: reg.cismet.de/uba/uim2020-html5-demonstrator:${CLIENT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        CLIENT_VERSION: ${CLIENT_VERSION}
    ports:
        - 80:80